### ISSUE TITLE
why pass the old value, and not use it? 

### ISSUE THREAD

**Issue by aric87** [gfed53/audio-swirl#2]
Creating variables takes memory. If you're not using it, don't create it 
https://github.com/gfed53/audio-swirl/blob/master/src/partials/search/searchController.js#L18

**Comment by gfed53** [comment]
For this:
$scope.$watch("search.searchTerm", function(newVal, oldVal){
        ahSearchTerm.set(newVal);
    });

This watches for changes in the search bar, so if the user switches over to a different tab and then return to it, they won't lose what they inputed (the value gets saved in the service). I think I need this for that to work, no?

**Comment by gfed53** [comment]
Oh never mind, I totally overlooked "old value"..
